### ISSUE TITLE
[Insight] Text files should end with a newline character - in Resources/config/services.yml, line 4

### ISSUE THREAD

**Issue by ghodkekrishna** [krushnaghodke/translation-bundle#2]
**[in Resources/config/services.yml, line 4](https://github.com/krushnaghodke/translation-bundle/blob/fd29338039907aa287250e14735e475a9c967d67/Resources/config/services.yml#L4)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
services:
    krushnaghodke.translation.manager:
        class: Krushnaghodke\TranslationBundle\Manager\TranslateManager
        arguments: [ '%krushnaghodke_yandex_translation.api_key%' ]
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/4548bbcf-df32-42a8-b1ae-9608622d60cf/analyses/1)_
